require("dotenv").config();
module.exports = {
  TWILLIO_ACCOUNT_SID: process.env.TWILLIO_ACCOUNT_SID,
  TWILLIO_AUTH_TOKEN: process.env.TWILLIO_AUTH_TOKEN,
  MPESA_CONSUMER_KEY: process.env.MPESA_CONSUMER_KEY,
  MPESA_CUSTOMER_SECRET: process.env.MPESA_CUSTOMER_SECRET,
  LIPA_NA_MPESA_PASS_KEY: process.env.LIPA_NA_MPESA_PASS_KEY,
  LIPA_NA_MPESA_SHORT_CODE: process.env.LIPA_NA_MPESA_SHORT_CODE,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,
};
